name: PCK.AUTOMIC_ANALYTICS_SCREENSHOTS
source: ae
binaries: 
- object: RESOURCES/LIBS/PCK.AUTOMIC_ANALYTICS_SCREENSHOTS.PRV.STORE
  resources: 
  - name: ANALYTICS.JAR
    type: BINARY
    path: tools/target/analytics-tool.jar
    version: 1.1.6
